Repository ca-cwds/county-admin, pull requests merged in 2019-03, with the labels that each got.

#341 COG-1270 Runs Firefox test container for Acceptance tests in integration
  JenkinsfileAcceptance
Labels: patch

#342 COG-1270 Fix failing acceptance tests
  spec/acceptance/user_list_office_spec.rb
Labels: patch

#343 COG-1258 Unlock locked users
  app/assets/stylesheets/application.scss
  app/controllers/api/user_detail_controller.rb
  app/javascript/_services/users/user.service.js
  app/javascript/_services/users/user.service.test.js
  app/javascript/actions/actionTypes.js
  app/javascript/actions/detailActions.js
  app/javascript/actions/detailActions.test.js
  app/javascript/common/Card.js
  app/javascript/common/Card.test.js
  app/javascript/containers/detailsContainer.js
  app/javascript/reducers/detailsReducers.js
  app/javascript/reducers/detailsReducers.test.js
  app/javascript/sagas/changeUserStatusSaga.js
  app/javascript/sagas/changeUserStatusSaga.test.js
  app/javascript/sagas/index.js
  app/javascript/selectors/detailSelector.js
  app/javascript/selectors/detailSelector.test.js
  app/javascript/views/userDetail/UserDetail.jsx
  app/javascript/views/userDetail/UserDetail.test.js
  app/javascript/views/userDetail/UserDetailEdit.jsx
  app/javascript/views/userDetail/UserDetailShow.jsx
  config/routes.rb
  lib/infrastructure/http_service.rb
  lib/users/user_details.rb
  lib/users/user_repository.rb
  spec/controllers/api/user_detail_controller_spec.rb
  spec/lib/infrastructure/http_service_spec.rb
  spec/lib/users/user_details_spec.rb
  spec/lib/users/user_repository_spec.rb
Labels: patch

#346 Reverting to edit mode independent on status
  app/assets/stylesheets/application.scss
  app/javascript/common/Card.js
  app/javascript/selectors/detailSelector.js
  app/javascript/selectors/detailSelector.test.js
  app/javascript/views/userDetail/UserDetail.jsx
Labels: patch

#344 COG-1270 Fix coverage issue inside container
  docker/test/Dockerfile.firefox
Labels: patch

#347 Test the build
  README.md
Labels: patch

#338 Cog 1244 immediate changeLog visibility
  app/javascript/actions/actionTypes.js
  app/javascript/actions/auditEventActions.js
  app/javascript/actions/auditEventActions.test.js
  app/javascript/actions/resendRegistrationEmailActions.js
  app/javascript/actions/resendRegistrationEmailActions.test.js
  app/javascript/containers/detailsContainer.js
  app/javascript/containers/usersListContainer.js
  app/javascript/reducers/auditEventsReducers.js
  app/javascript/reducers/auditEventsReducers.test.js
  app/javascript/reducers/resendRegistrationEmailReducers.js
  app/javascript/reducers/resendRegistrationEmailReducers.test.js
  app/javascript/sagas/resendRegistrationEmailSaga.js
  app/javascript/sagas/resendRegistrationEmailSaga.test.js
  app/javascript/sagas/saveUserDetailsSaga.js
  app/javascript/sagas/saveUserDetailsSaga.test.js
  app/javascript/selectors/auditEventsSelector.js
  app/javascript/selectors/auditEventsSelector.test.js
  app/javascript/selectors/detailSelector.js
  app/javascript/selectors/detailSelector.test.js
  app/javascript/selectors/userListSelector.js
  app/javascript/selectors/userListSelector.test.js
  app/javascript/views/userDetail/UserDetail.jsx
  app/javascript/views/userDetail/UserDetail.test.js
  lib/elastic/audit_event_query_builder.rb
  lib/users/user_repository.rb
  spec/acceptance/add_user_spec.rb
  spec/acceptance/support/user_detail_page_helpers.rb
  spec/acceptance/support/user_list_page_helpers.rb
  spec/lib/elastic/audit_event_query_builder_spec.rb
  spec/lib/users/user_repository_spec.rb
Labels: patch

#348 Cog 1244 immediate changelog visibility
  app/javascript/containers/usersListContainer.js
  app/javascript/reducers/auditEventsReducers.js
  app/javascript/reducers/auditEventsReducers.test.js
  app/javascript/sagas/getAuditEventsSaga.js
  app/javascript/sagas/getAuditEventsSaga.test.js
  app/javascript/sagas/resendRegistrationEmailSaga.js
  app/javascript/sagas/resendRegistrationEmailSaga.test.js
  app/javascript/sagas/saveUserDetailsSaga.js
  app/javascript/sagas/saveUserDetailsSaga.test.js
  app/javascript/views/usersList/UsersList.jsx
  app/javascript/views/usersList/UsersList.test.js
Labels: patch

#349 Update sorting on changelog to include always-descending-by-timestamp…
  app/javascript/testing/setupTests.js
  app/javascript/views/userDetail/ChangeLog.jsx
  app/javascript/views/userDetail/ChangeLog.test.js
  lib/users/user_repository.rb
Labels: patch

#345 FIT-369-Smoke-test-in-cap/county-admin
  JenkinsDeploy
  Jenkinsfile
  docker/test/Dockerfile
Labels: patch

#350 COG-1220 Disable hyperlinks for Phone Number
  app/javascript/views/addUser/AddUser.jsx
  app/javascript/views/addUser/AddUser.test.js
  app/javascript/views/userDetail/UserDetail.jsx
  app/javascript/views/userDetail/UserDetail.test.js
Labels: patch

#351 Make sorting on changelog case-insensitive
  app/javascript/views/userDetail/ChangeLog.jsx
  app/javascript/views/userDetail/ChangeLog.test.js
Labels: bug, patch

#352 Cog 1194 parameterize racfid in acceptance
  JenkinsDeploy
  JenkinsfileAcceptance
  spec/acceptance/add_user_spec.rb
  spec/acceptance_helper.rb
Labels: minor

#353 Fix jenkins params
  JenkinsDeploy
Labels: patch

#356 COG-1194 Fix jenkins pipeline
  JenkinsDeploy
Labels: patch

#354 COG-1220 Disable the Hyperlinks in Show/Edit and add user page
  app/javascript/views/addUser/AddUser.jsx
  app/javascript/views/userDetail/UserDetail.jsx
  app/javascript/views/userDetail/UserDetail.test.js
  app/javascript/views/userDetail/UserDetailEdit.jsx
  app/javascript/views/userDetail/UserDetailEdit.test.js
  app/javascript/views/userDetail/UserDetailShow.jsx
  app/javascript/views/userDetail/UserDetailShow.test.js
Labels: patch

#355 COG-1315-Account locked changelog status
  app/javascript/_utils/formatters.js
  app/javascript/_utils/formatters.test.js
  app/javascript/views/userDetail/ChangeLog.jsx
Labels: patch

#357 COG-1220 Disable hyperlinks in specific tags for phone number fields
  app/javascript/views/addUser/AddUser.jsx
  app/javascript/views/addUser/AddUser.test.js
  app/javascript/views/addUser/AddVerifiedUser.jsx
  app/javascript/views/addUser/AddVerifiedUser.test.js
  app/javascript/views/userDetail/UserDetailEdit.jsx
  app/javascript/views/userDetail/UserDetailEdit.test.js
  app/javascript/views/userDetail/UserDetailShow.jsx
  app/javascript/views/userDetail/UserDetailShow.test.js
Labels: patch

#359 Exercise the browser, stabilize the driver before checking accessibility
  Gemfile
  Gemfile.lock
  spec/acceptance/support/user_list_page_helpers.rb
  spec/acceptance/user_forgot_password_spec.rb
  spec/acceptance/user_list_page_spec.rb
  spec/acceptance/user_login_spec.rb
Labels: patch

#358 Use meta tag in page header instead of specific tag for field
  app/javascript/views/addUser/AddVerifiedUser.jsx
  app/javascript/views/addUser/AddVerifiedUser.test.js
  app/javascript/views/userDetail/UserDetailEdit.jsx
  app/javascript/views/userDetail/UserDetailEdit.test.js
  app/javascript/views/userDetail/UserDetailShow.jsx
  app/javascript/views/userDetail/UserDetailShow.test.js
  app/views/layouts/application.html.erb
Labels: patch

#360 Rename 'Notes And Details' chanelog column to 'Details' and disable s…
  app/javascript/views/userDetail/ChangeLog.jsx
  app/javascript/views/userDetail/ChangeLog.test.js
Labels: patch

#362 COG 1257 Do not show(0) in components that have counts
  app/javascript/views/userDetail/CWSPrivileges.jsx
  app/javascript/views/userDetail/CWSPrivileges.test.js
  app/javascript/views/userDetail/ChangeLog.jsx
  app/javascript/views/userDetail/ChangeLog.test.js
Labels: patch

#364 Move sort disabling to the right attribute location
  app/javascript/views/userDetail/ChangeLog.jsx
Labels: patch

#363 COG-1262 Change log should not update when navigating through pages in user list
  app/javascript/_services/users/user.service.js
  app/javascript/sagas/searchUsersSaga.js
  app/javascript/sagas/searchUsersSaga.test.js
  app/javascript/views/usersList/UsersList.jsx
  app/javascript/views/usersList/UsersList.test.js
Labels: patch

#361 COG-1320 Change success alert message text when email is edited
  app/assets/stylesheets/application.scss
  app/javascript/common/UserMessage.js
  app/javascript/common/UserMessage.test.js
  app/javascript/sagas/saveUserDetailsSaga.js
  app/javascript/sagas/saveUserDetailsSaga.test.js
  app/javascript/views/userDetail/UserDetail.jsx
  app/javascript/views/userDetail/UserDetail.test.js
Labels: patch
