Repository ca-cwds/county-admin, pull requests merged in 2019-02, with the labels that each got.

#307 Adds optional parameter when rebuilding for Jenkins UI master builds
  Jenkinsfile
Labels: patch

#310 Fix for the Jenkins master build
  Jenkinsfile
  JenkinsfileCodeReview
Labels: patch

#311 COG-520 Edit and save notes for a user.
  app/assets/stylesheets/application.scss
  app/controllers/api/user_detail_controller.rb
  app/javascript/containers/detailsContainer.js
  app/javascript/selectors/detailSelector.js
  app/javascript/selectors/detailSelector.test.js
  app/javascript/views/userDetail/Notes.jsx
  app/javascript/views/userDetail/Notes.test.js
  app/javascript/views/userDetail/UserDetail.jsx
  app/javascript/views/userDetail/UserDetail.test.js
  lib/users/user_details.rb
  spec/controllers/api/user_detail_controller_spec.rb
  spec/lib/users/user_details_spec.rb
Labels: patch

#314 COG-520 Fix detail view mode when user is not editable
  app/javascript/views/userDetail/Notes.jsx
  app/javascript/views/userDetail/Notes.test.js
Labels: patch

#313 Cog 1203 import buttons from component library
  app/assets/stylesheets/application.scss
  app/javascript/common/Card.js
  app/javascript/views/userDetail/Modal.jsx
  app/javascript/views/userDetail/UserDetailEdit.jsx
  app/javascript/views/usersList/UsersList.jsx
Labels: patch

#308 Update sorting on changelog, use secondary sorting by admin name + timestamp
  app/javascript/views/userDetail/ChangeLog.jsx
  app/javascript/views/userDetail/ChangeLog.test.js
  spec/acceptance/add_user_spec.rb
  spec/acceptance/support/user_detail_page_helpers.rb
  spec/acceptance/support/user_list_page_helpers.rb
  spec/acceptance/user_edit_details_spec.rb
Labels: patch

#315 Fix resend invite click
  spec/acceptance/add_user_spec.rb
  spec/acceptance/user_edit_details_spec.rb
Labels: patch

#316 COG-1169 Change Page Header Button Colors
  app/assets/stylesheets/application.scss
Labels: patch

#318 COG-1169 Fix Tabbing issue for buttons
  app/javascript/common/PageHeaderButtons.js
Labels: patch

#317 Add secondary sort of timestamp to event_type
  app/javascript/views/userDetail/ChangeLog.jsx
  app/javascript/views/userDetail/ChangeLog.test.js
Labels: patch

#320 COG-1234 Actions/Saga/Reducer for audit events
  app/javascript/_services/users/user.service.js
  app/javascript/_services/users/user.service.test.js
  app/javascript/actions/actionTypes.js
  app/javascript/actions/auditEventActions.js
  app/javascript/actions/auditEventActions.test.js
  app/javascript/containers/usersListContainer.js
  app/javascript/reducers/auditEventsReducers.js
  app/javascript/reducers/auditEventsReducers.test.js
  app/javascript/reducers/index.js
  app/javascript/sagas/getAuditEventsSaga.js
  app/javascript/sagas/getAuditEventsSaga.test.js
  app/javascript/sagas/index.js
  app/javascript/sagas/searchUsersSaga.js
  app/javascript/sagas/searchUsersSaga.test.js
Labels: patch

#323 Prettier printwidth increase
  .eslintrc-common.js
  app/javascript/_constants/constants.test.js
  app/javascript/_utils/formatters.test.js
  app/javascript/common/DropDown.js
  app/javascript/common/GlobalHeader.js
  app/javascript/reducers/detailsReducers.test.js
  app/javascript/reducers/userListReducers.js
  app/javascript/sagas/getChangeLogDetailsSaga.test.js
  app/javascript/sagas/saveUserDetailsSaga.test.js
  app/javascript/selectors/changeLogDetailsSelector.test.js
  app/javascript/selectors/detailSelector.js
  app/javascript/selectors/detailSelector.test.js
  app/javascript/selectors/officeListSelector.test.js
  app/javascript/selectors/permissionsListSelector.test.js
  app/javascript/selectors/validateNewUserSelector.test.js
  app/javascript/views/addUser/AddVerifiedUser.jsx
  app/javascript/views/addUser/AddVerifiedUser.test.js
  app/javascript/views/addUser/VerifyUser.jsx
  app/javascript/views/userDetail/ChangeLog.test.js
  app/javascript/views/userDetail/UserDetail.jsx
  app/javascript/views/userDetail/UserDetail.test.js
  app/javascript/views/userDetail/UserDetailEdit.test.js
  app/javascript/views/userDetail/UserDetailShow.test.js
  app/javascript/views/usersList/UsersList.test.js
Labels: patch

#319 Code 146 resolve cc issues - part 1
  .codeclimate.yml
  app/javascript/views/userDetail/UserDetail.jsx
  app/javascript/views/usersList/Pagination.jsx
Labels: patch

#327 COG-1067 Handle audit log ES query failure
  app/controllers/api/audit_events_controller.rb
  lib/audit_events/audit_event_repository.rb
  spec/controllers/api/audit_events_controller_spec.rb
Labels: patch

#322 COG-804 Privileges from CWS-CMS
  app/javascript/containers/detailsContainer.js
  app/javascript/selectors/detailSelector.js
  app/javascript/selectors/detailSelector.test.js
  app/javascript/views/userDetail/CWSPermissions.jsx
  app/javascript/views/userDetail/CWSPermissions.test.js
  app/javascript/views/userDetail/CWSPrivileges.jsx
  app/javascript/views/userDetail/CWSPrivileges.test.js
  app/javascript/views/userDetail/UserDetail.jsx
  app/javascript/views/userDetail/UserDetail.test.js
  app/javascript/views/usersList/UsersList.scss
Labels: enhancement, minor

#329 FIT-396 - Preserve the Jenkins Build in the County Admin App
  Jenkinsfile
  JenkinsfileCodeReview
Labels: patch

#324 Cog 776 warn admin when permissions empty
  app/assets/stylesheets/application.scss
  app/javascript/common/PageHeaderButtons.test.js
  app/javascript/containers/detailsContainer.js
  app/javascript/selectors/detailSelector.js
  app/javascript/selectors/detailSelector.test.js
  app/javascript/views/userDetail/ChangeLog.jsx
  app/javascript/views/userDetail/ChangeLogDetailsView.jsx
  app/javascript/views/userDetail/ChangeLogDetailsView.test.js
  app/javascript/views/userDetail/DetailsPageHeaderButtons.jsx
  app/javascript/views/userDetail/DetailsPageHeaderButtons.test.js
  app/javascript/views/userDetail/NoPermissionsWarning.jsx
  app/javascript/views/userDetail/NoPermissionsWarning.test.js
  app/javascript/views/userDetail/UserDetail.jsx
  app/javascript/views/userDetail/UserDetail.test.js
Labels: enhancement, patch

#328 Code 146 resolve cc issues Part-2
  .codeclimate.yml
  app/javascript/_utils/checkAdminRoles.js
  app/javascript/_utils/checkAdminRoles.test.js
  app/javascript/reducers/userListReducers.js
  app/javascript/views/userDetail/ChangeLog.jsx
  app/javascript/views/userDetail/UserDetail.jsx
  app/javascript/views/usersList/UsersList.jsx
Labels: patch

#325 COG-1235 Add Change Log to User List View
  app/javascript/containers/usersListContainer.js
  app/javascript/reducers/auditEventsReducers.js
  app/javascript/reducers/auditEventsReducers.test.js
  app/javascript/reducers/index.js
  app/javascript/selectors/userListSelector.js
  app/javascript/selectors/userListSelector.test.js
  app/javascript/views/userDetail/ChangeLog.jsx
  app/javascript/views/userDetail/ChangeLog.test.js
  app/javascript/views/userDetail/ChangeLogDetailsView.jsx
  app/javascript/views/userDetail/ChangeLogDetailsView.test.js
  app/javascript/views/usersList/UsersList.jsx
  app/javascript/views/usersList/UsersList.scss
  app/javascript/views/usersList/UsersList.test.js
Labels: enhancement, patch

#330 Add cws_privileges to user_details
  lib/users/user_details.rb
  spec/lib/users/user_details_spec.rb
Labels: patch

#331 Changes are not immediately seen in Change Log when the event is Resend Invite
  app/javascript/sagas/resendRegistrationEmailSaga.js
  app/javascript/sagas/resendRegistrationEmailSaga.test.js
Labels: patch

#332 Look for confirm message when adding users.
  spec/acceptance/support/login_helper.rb
  spec/acceptance/support/user_list_page_helpers.rb
  spec/acceptance/user_list_office_spec.rb
Labels: minor

#333 COG-1221 Fix emoji's character count on Notes Field.
  app/javascript/selectors/detailSelector.test.js
  app/javascript/views/userDetail/Notes.jsx
  app/javascript/views/userDetail/Notes.test.js
Labels: patch

#334 COG-1067 Add Made To Column in change log
  app/javascript/_services/users/user.service.js
  app/javascript/_services/users/user.service.test.js
  app/javascript/views/userDetail/ChangeLog.jsx
  app/javascript/views/userDetail/ChangeLog.test.js
Labels: patch

#336 Fix the pagination styles in IE, Edge, fire-fox browsers
  app/javascript/views/usersList/Pagination.jsx
  app/javascript/views/usersList/UsersList.scss
Labels: patch

#335 Cog 1067 make audit log search query safer
  app/controllers/api/audit_events_controller.rb
  app/javascript/selectors/userListSelector.js
  app/javascript/selectors/userListSelector.test.js
  lib/audit_events/audit_event_repository.rb
  spec/controllers/api/audit_events_controller_spec.rb
Labels: patch

#337 COG-1150 pagination style fix IE-browser
  app/javascript/views/usersList/UsersList.scss
Labels: patch
